from django.db import migrations, models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone

class Migration(migrations.Migration):
    initial = True
    dependencies = [('auth', '0012_alter_user_first_name_max_length')]
    operations = [migrations.CreateModel(name='User', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('password', models.CharField(max_length=128, verbose_name='password')), ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')), ('is_superuser', models.BooleanField(default=False)), ('username', models.CharField(blank=True, max_length=150)), ('first_name', models.CharField(blank=True, max_length=150)), ('last_name', models.CharField(blank=True, max_length=150)), ('is_staff', models.BooleanField(default=False)), ('is_active', models.BooleanField(default=True)), ('date_joined', models.DateTimeField(default=django.utils.timezone.now)), ('email', models.EmailField(max_length=254, unique=True)), ('student_id', models.CharField(blank=True, max_length=40, null=True, unique=True)), ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Administrator')], default='student', max_length=20)), ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')), ('created_at', models.DateTimeField(auto_now_add=True)), ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group')), ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission'))], options={'indexes': [models.Index(fields=['email'], name='authenticati_email_0f6b0c_idx'), models.Index(fields=['student_id'], name='authenticati_student_2d96f0_idx')]}, managers=[('objects', django.contrib.auth.models.UserManager())])]
