import {Link} from 'react-router-dom'; import {Bar,BarChart,CartesianGrid,Cell,Line,LineChart,Pie,PieChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
const data=[{name:'Mon',score:72},{name:'Tue',score:80},{name:'Wed',score:76},{name:'Thu',score:88},{name:'Fri',score:92}];
export function Dashboard(){return <div className="space-y-6"><h1 className="text-4xl font-black">Welcome back, STEM learner</h1><div className="grid gap-4 md:grid-cols-5">{['Total Quizzes','Highest Score','Average Score','Total Subjects','Completion'].map((s,i)=><div className="card"><p>{s}</p><b className="text-3xl text-primary">{[12,'98%','84%',4,'73%'][i]}</b></div>)}</div><div className="grid gap-6 md:grid-cols-2"><Chart title="Weekly Progress"/><Chart title="Score Trend"/></div><div className="card"><h2 className="font-bold">Quick Actions</h2><Link className="btn-primary mt-4 inline-block" to="/subjects">Start Quiz</Link></div></div>}
function Chart({title}:{title:string}){return <div className="card h-80"><h2 className="font-bold">{title}</h2><ResponsiveContainer><LineChart data={data}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Line dataKey="score" stroke="#4f46e5" strokeWidth={3}/></LineChart></ResponsiveContainer></div>}
export function Subjects(){return <div><h1 className="text-4xl font-black">Choose a STEM Subject</h1><div className="mt-6 grid gap-5 md:grid-cols-4">{['Mathematics','Science','Technology','Engineering'].map((s,i)=><div className="card"><div className="h-32 rounded-2xl bg-gradient-to-br from-blue-400 to-purple-500"/><h2 className="mt-4 text-xl font-bold">{s}</h2><p>Build core knowledge through interactive quizzes.</p><p className="mt-2">Difficulty: {['Beginner','Intermediate','Advanced','Mixed'][i]}</p><p>Quizzes: {8+i}</p><progress className="w-full" value={40+i*12} max={100}/><Link className="btn-primary mt-4 inline-block" to="/quiz/1">Start Quiz</Link></div>)}</div></div>}
export function QuizPage(){return <div className="grid gap-6 lg:grid-cols-[1fr_280px]"><section className="card"><progress className="w-full" value={60} max={100}/><p className="mt-4">Question 3 of 5 · Auto-saved · Current Score 2</p><h1 className="mt-4 text-3xl font-black">What is the value of π rounded to two decimals?</h1><div className="mt-6 grid gap-3">{['3.14','2.71','1.62','9.81'].map((o,i)=><button className="rounded-2xl border p-4 text-left hover:border-primary">{o}</button>)}</div><div className="mt-6 rounded-2xl bg-green-50 p-4 text-green-700">Correct answer: 3.14. Explanation: π is the ratio of circumference to diameter. Great work!</div><div className="mt-6 flex justify-between"><button className="btn">Previous</button><button className="btn-primary">Next</button><Link className="btn-primary" to="/results">Submit Quiz</Link></div></section><aside className="card"><h2 className="font-bold">Navigation</h2><div className="mt-4 grid grid-cols-5 gap-2">{[1,2,3,4,5].map(n=><button className="rounded-xl bg-blue-100 p-3 dark:bg-slate-800">{n}</button>)}</div></aside></div>}
export function Results(){return <div className="grid gap-6 md:grid-cols-2"><div className="card text-center"><h1 className="text-4xl font-black">Gold Performance</h1><p className="text-7xl font-black text-primary">92%</p><p>Final Score 23/25 · Correct 23 · Incorrect 2 · Time 18m</p><Link className="btn-primary mt-6 inline-block" to="/quiz/1">Retake Quiz</Link><Link className="btn mt-6 ml-3 inline-block" to="/dashboard">Return Dashboard</Link></div><div className="card h-80"><ResponsiveContainer><BarChart data={data}><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="score" fill="#9333ea"/></BarChart></ResponsiveContainer></div></div>}
export function History(){return <div className="card"><h1 className="text-3xl font-black">Score History</h1><input className="my-4 rounded-xl border p-3" placeholder="Search"/><table className="w-full text-left"><thead><tr>{['Date','Subject','Quiz','Score','Percentage','Time Taken','Status'].map(h=><th>{h}</th>)}</tr></thead><tbody><tr><td>2026-07-20</td><td>Math</td><td>Algebra</td><td>18/20</td><td>90%</td><td>14m</td><td>Passed</td></tr></tbody></table><button className="btn-primary mt-4">Export CSV</button></div>}
export function Reports(){return <div className="space-y-6"><h1 className="text-4xl font-black">Performance Reports</h1><div className="grid gap-4 md:grid-cols-5">{['Highest','Lowest','Average','Completed','Streak'].map((s,i)=><div className="card"><p>{s}</p><b>{['98%','61%','84%',12,'7 days'][i]}</b></div>)}</div><div className="grid gap-6 md:grid-cols-3"><Chart title="Weekly Progress"/><div className="card h-80"><ResponsiveContainer><PieChart><Pie data={[{name:'Correct',value:82},{name:'Incorrect',value:18}]} dataKey="value"><Cell fill="#22c55e"/><Cell fill="#ef4444"/></Pie></PieChart></ResponsiveContainer></div><div className="card"><h2 className="font-bold">Recommendations</h2><ul className="list-disc p-5"><li>Review Algebra</li><li>Practice Geometry</li><li>Improve Scientific Concepts</li></ul><button className="btn-primary">Export PDF / CSV</button></div></div></div>}
export function Admin(){return <div className="space-y-6"><h1 className="text-4xl font-black">Admin Dashboard</h1><div className="grid gap-4 md:grid-cols-5">{['Total Students','Total Subjects','Total Quizzes','Total Questions','Average Scores'].map((s,i)=><div className="card"><p>{s}</p><b>{[1240,4,88,520,'82%'][i]}</b></div>)}</div><div className="grid gap-4 md:grid-cols-4">{['Student','Subject','Quiz','Question'].map(x=><div className="card"><h2 className="font-bold">{x} Management</h2><p>Search, create, edit, delete, view reports and history.</p><button className="btn-primary mt-4">Manage</button></div>)}</div></div>}
export const Forbidden=()=> <div className="card"><h1 className="text-4xl font-black">403 Access Denied</h1><p>You do not have permission to view this page.</p></div>;
